# Generated by Django 3.2.3 on 2021-05-30 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teammanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniClass',
            fields=[
                ('alumni_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Alumni Class',
                'verbose_name_plural': 'Alumni Classes',
                'db_table': 'AlumniClass',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='AlumniPlayer',
            fields=[
                ('alumni_player_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=50)),
                ('college_roster_link', models.URLField(max_length=75, unique=True)),
                ('college_roster_photo', models.ImageField(upload_to='alumni-portraits')),
                ('alumni_class', models.ForeignKey(db_column='alumni_class_id', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='alumni.alumniclass', verbose_name='Alumni Class')),
                ('info', models.ForeignKey(blank=True, db_column='player_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='teammanagement.player', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Alumni Player',
                'verbose_name_plural': 'Alumni Players',
                'db_table': 'AlumniPlayer',
                'ordering': ['last_name'],
            },
        ),
    ]
