# Generated by Django 3.2.12 on 2022-05-10 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgradprep', '0001_initial'),
        ('alumni', '0003_auto_20220509_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniplayer',
            name='college_name',
        ),
        migrations.AlterField(
            model_name='alumniplayer',
            name='college',
            field=models.ForeignKey(db_column='college_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='alumni_players', to='postgradprep.college', verbose_name='College'),
            preserve_default=False,
        ),
    ]
