# Generated by Django 3.2.12 on 2022-08-14 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("colleges", "0001_initial"),
        ("alumni", "0005_auto_20220510_1924"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="alumniplayer",
                    name="college",
                    field=models.ForeignKey(
                        db_column="college_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumni_players",
                        to="colleges.college",
                        verbose_name="College",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
