# Generated by Django 3.2.12 on 2022-05-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgradprep', '0002_collegecamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegecamp',
            options={'verbose_name': 'College Camp', 'verbose_name_plural': 'College Camps'},
        ),
    ]
