# Generated by Django 3.1.6 on 2021-04-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayer',
            name='roster_photo',
            field=models.ImageField(default=0, upload_to='player-portraits'),
            preserve_default=False,
        ),
    ]
