# Generated by Django 3.1.6 on 2021-04-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanagement', '0002_auto_20210407_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_photo',
            field=models.ImageField(blank=True, null=True, upload_to='team-photos'),
        ),
        migrations.AlterField(
            model_name='teamcoach',
            name='roster_photo',
            field=models.ImageField(default='yes', upload_to='coach-portraits'),
            preserve_default=False,
        ),
    ]
