# Generated by Django 3.2.7 on 2021-09-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-is_active', 'last_name']},
        ),
    ]
