# Generated by Django 3.2.7 on 2021-09-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammanagement', '0002_alter_player_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamcoach',
            old_name='info',
            new_name='personal_info',
        ),
        migrations.RenameField(
            model_name='teamplayer',
            old_name='info',
            new_name='personal_info',
        ),
    ]
