# Generated by Django 3.2.12 on 2022-05-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanagement', '0004_auto_20210925_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_link',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, unique=True),
        ),
    ]
