# Generated by Django 3.2.12 on 2022-04-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'City',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abbr', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'State',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zip_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'verbose_name': 'Zip Code',
                'verbose_name_plural': 'Zip Codes',
                'db_table': 'ZipCode',
            },
        ),
    ]
