# Generated by Django 3.2.3 on 2021-06-13 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teammanagement', '0001_initial'),
        ('playerprogress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distancetype',
            options={'ordering': ['order'], 'verbose_name': 'Distance Type', 'verbose_name_plural': 'Distance Types'},
        ),
        migrations.AlterModelOptions(
            name='lifttype',
            options={'ordering': ['order'], 'verbose_name': 'Lift Type', 'verbose_name_plural': 'Lift Types'},
        ),
        migrations.AlterModelOptions(
            name='timetype',
            options={'ordering': ['order'], 'verbose_name': 'Time Type', 'verbose_name_plural': 'Time Types'},
        ),
        migrations.AlterModelOptions(
            name='velocitytype',
            options={'ordering': ['order'], 'verbose_name': 'Velocity Type', 'verbose_name_plural': 'Velocity Types'},
        ),
        migrations.AddField(
            model_name='distancetype',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lifttype',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timetype',
            name='is_speed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timetype',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='velocitytype',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bodyweight',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='body_weights', to='teammanagement.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='bodyweightimprovement',
            name='baseline',
            field=models.ForeignKey(db_column='baseline_body_weight_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baseline_body_weight_improvements', to='playerprogress.bodyweight', verbose_name='Baseline'),
        ),
        migrations.AlterField(
            model_name='bodyweightimprovement',
            name='latest',
            field=models.ForeignKey(db_column='latest_body_weight_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_body_weight_improvements', to='playerprogress.bodyweight', verbose_name='Latest'),
        ),
        migrations.AlterField(
            model_name='bodyweightimprovement',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='body_weight_improvements', to='teammanagement.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='teammanagement.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='ttype',
            field=models.ForeignKey(db_column='distance_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='distances', to='playerprogress.distancetype', verbose_name='Distance Type'),
        ),
        migrations.AlterField(
            model_name='distanceimprovement',
            name='baseline',
            field=models.ForeignKey(db_column='baseline_distance_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baseline_distance_improvements', to='playerprogress.distance', verbose_name='Baseline'),
        ),
        migrations.AlterField(
            model_name='distanceimprovement',
            name='latest',
            field=models.ForeignKey(db_column='latest_distance_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_distance_improvements', to='playerprogress.distance', verbose_name='Latest'),
        ),
        migrations.AlterField(
            model_name='distanceimprovement',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='distance_improvements', to='teammanagement.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='distanceimprovement',
            name='ttype',
            field=models.ForeignKey(db_column='distance_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='improvements', to='playerprogress.distancetype', verbose_name='Distance Type'),
        ),
        migrations.AlterField(
            model_name='lift',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='lifts', to='teammanagement.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='lift',
            name='ttype',
            field=models.ForeignKey(db_column='lift_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='lifts', to='playerprogress.lifttype', verbose_name='Lift Type'),
        ),
        migrations.AlterField(
            model_name='liftimprovement',
            name='baseline',
            field=models.ForeignKey(db_column='baseline_lift_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baseline_lift_improvements', to='playerprogress.lift', verbose_name='Baseline'),
        ),
        migrations.AlterField(
            model_name='liftimprovement',
            name='latest',
            field=models.ForeignKey(db_column='latest_lift_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_lift_improvements', to='playerprogress.lift', verbose_name='Latest'),
        ),
        migrations.AlterField(
            model_name='liftimprovement',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='lift_improvements', to='teammanagement.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='liftimprovement',
            name='ttype',
            field=models.ForeignKey(db_column='lift_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='improvements', to='playerprogress.lifttype', verbose_name='Lift Type'),
        ),
        migrations.AlterField(
            model_name='strengthincrement',
            name='lift_set',
            field=models.ForeignKey(db_column='lift_set_id', on_delete=django.db.models.deletion.PROTECT, related_name='strength_increments', to='playerprogress.liftset', verbose_name='Set Weight x Reps'),
        ),
        migrations.AlterField(
            model_name='strengthincrement',
            name='lift_type',
            field=models.ForeignKey(db_column='lift_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='strength_increments', to='playerprogress.lifttype', verbose_name='Lift Type'),
        ),
        migrations.AlterField(
            model_name='time',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='times', to='teammanagement.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='time',
            name='ttype',
            field=models.ForeignKey(db_column='time_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='times', to='playerprogress.timetype', verbose_name='Time Type'),
        ),
        migrations.AlterField(
            model_name='timeimprovement',
            name='baseline',
            field=models.ForeignKey(db_column='baseline_time_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baseline_time_improvements', to='playerprogress.time', verbose_name='Baseline'),
        ),
        migrations.AlterField(
            model_name='timeimprovement',
            name='latest',
            field=models.ForeignKey(db_column='latest_time_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_time_improvements', to='playerprogress.time', verbose_name='Latest'),
        ),
        migrations.AlterField(
            model_name='timeimprovement',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='time_improvements', to='teammanagement.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='timeimprovement',
            name='ttype',
            field=models.ForeignKey(db_column='time_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='improvements', to='playerprogress.timetype', verbose_name='Time Type'),
        ),
        migrations.AlterField(
            model_name='velocity',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='velocities', to='teammanagement.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='velocity',
            name='ttype',
            field=models.ForeignKey(db_column='velocity_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='velocities', to='playerprogress.velocitytype', verbose_name='Velocity Type'),
        ),
        migrations.AlterField(
            model_name='velocityimprovement',
            name='baseline',
            field=models.ForeignKey(db_column='baseline_velocity_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baseline_velocity_improvements', to='playerprogress.velocity', verbose_name='Baseline'),
        ),
        migrations.AlterField(
            model_name='velocityimprovement',
            name='latest',
            field=models.ForeignKey(db_column='latest_velocity_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_velocity_improvements', to='playerprogress.velocity', verbose_name='Latest'),
        ),
        migrations.AlterField(
            model_name='velocityimprovement',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='velocity_improvements', to='teammanagement.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='velocityimprovement',
            name='ttype',
            field=models.ForeignKey(db_column='velocity_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='improvements', to='playerprogress.velocitytype', verbose_name='Velocity Type'),
        ),
    ]
