# Generated by Django 3.2.12 on 2022-08-03 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teammanagement", "0005_alter_player_player_link"),
        ("playerprogress", "0008_pulldown"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="velocity",
                    name="player",
                ),
                migrations.RemoveField(
                    model_name="velocity",
                    name="ttype",
                ),
                migrations.RemoveField(
                    model_name="velocityimprovement",
                    name="baseline",
                ),
                migrations.RemoveField(
                    model_name="velocityimprovement",
                    name="latest",
                ),
                migrations.RemoveField(
                    model_name="velocityimprovement",
                    name="player",
                ),
                migrations.RemoveField(
                    model_name="velocityimprovement",
                    name="ttype",
                ),
                migrations.AlterField(
                    model_name="bodyweight",
                    name="player",
                    field=models.ForeignKey(
                        db_column="player_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bodyweight_records",
                        to="teammanagement.player",
                        verbose_name="Player",
                    ),
                ),
                migrations.AlterField(
                    model_name="distance",
                    name="player",
                    field=models.ForeignKey(
                        db_column="player_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distance_records",
                        to="teammanagement.player",
                        verbose_name="Player",
                    ),
                ),
                migrations.AlterField(
                    model_name="lift",
                    name="player",
                    field=models.ForeignKey(
                        db_column="player_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lift_records",
                        to="teammanagement.player",
                        verbose_name="Player",
                    ),
                ),
                migrations.AlterField(
                    model_name="time",
                    name="player",
                    field=models.ForeignKey(
                        db_column="player_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_records",
                        to="teammanagement.player",
                        verbose_name="Player",
                    ),
                ),
                migrations.DeleteModel(
                    name="Pulldown",
                ),
                migrations.DeleteModel(
                    name="Velocity",
                ),
                migrations.DeleteModel(
                    name="VelocityImprovement",
                ),
                migrations.DeleteModel(
                    name="VelocityType",
                ),
            ],
            database_operations=[],
        ),
    ]
