# Generated by Django 3.2.12 on 2022-08-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerprogress', '0009_auto_20220803_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distanceimprovement',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='distanceimprovement',
            name='latest',
        ),
        migrations.RemoveField(
            model_name='distanceimprovement',
            name='player',
        ),
        migrations.RemoveField(
            model_name='distanceimprovement',
            name='ttype',
        ),
        migrations.RemoveField(
            model_name='liftimprovement',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='liftimprovement',
            name='latest',
        ),
        migrations.RemoveField(
            model_name='liftimprovement',
            name='player',
        ),
        migrations.RemoveField(
            model_name='liftimprovement',
            name='ttype',
        ),
        migrations.RemoveField(
            model_name='timeimprovement',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='timeimprovement',
            name='latest',
        ),
        migrations.RemoveField(
            model_name='timeimprovement',
            name='player',
        ),
        migrations.RemoveField(
            model_name='timeimprovement',
            name='ttype',
        ),
        migrations.DeleteModel(
            name='BodyWeightImprovement',
        ),
        migrations.DeleteModel(
            name='DistanceImprovement',
        ),
        migrations.DeleteModel(
            name='LiftImprovement',
        ),
        migrations.DeleteModel(
            name='TimeImprovement',
        ),
    ]
