# Generated by Django 3.1.6 on 2021-04-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumniplayer',
            options={'ordering': ['last_name'], 'verbose_name': 'Alumni Player', 'verbose_name_plural': 'Alumni Players'},
        ),
    ]
