# Generated by Django 3.2.12 on 2022-05-08 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumniplayer',
            old_name='college',
            new_name='college_name',
        ),
    ]
