# Generated by Django 3.2.12 on 2022-05-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgradprep', '0001_initial'),
        ('alumni', '0002_rename_college_alumniplayer_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniplayer',
            name='college',
            field=models.ForeignKey(blank=True, db_column='college_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alumni_players', to='postgradprep.college', verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='alumniplayer',
            name='alumni_class',
            field=models.ForeignKey(db_column='alumni_class_id', on_delete=django.db.models.deletion.PROTECT, related_name='players', to='alumni.alumniclass', verbose_name='Alumni Class'),
        ),
        migrations.AlterField(
            model_name='alumniplayer',
            name='college_roster_photo',
            field=models.ImageField(blank=True, null=True, upload_to='alumni-portraits'),
        ),
    ]
