# Generated by Django 3.2.12 on 2022-05-10 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teammanagement', '0005_alter_player_player_link'),
        ('alumni', '0004_auto_20220510_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumniplayer',
            options={'ordering': ['info__last_name'], 'verbose_name': 'Alumni Player', 'verbose_name_plural': 'Alumni Players'},
        ),
        migrations.RemoveField(
            model_name='alumniplayer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='alumniplayer',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='alumniplayer',
            name='info',
            field=models.ForeignKey(db_column='player_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='teammanagement.player', verbose_name='Player'),
            preserve_default=False,
        ),
    ]
