version: "3.7"

services:
  app:
    container_name: hempfieldbaseball
    build:
      context: .
    command: >
      sh -c "sleep 30 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=HempfieldBaseball
      - DATABASE_USER=hempfield_baseball_admin
      - DATABASE_PASSWORD=hempfield
      - DATABASE_PORT=3306
      - SECRET_KEY=+(s(6n1%0gw*%*21ai7n9n9!4#4^52#p^@-3pc90x68+og*fw8
      - STATIC_ROOT=~/projects/tmp
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - .docker:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hempfield
      - MYSQL_DATABASE=HempfieldBaseball
      - MYSQL_USER=hempfield_baseball_admin
      - MYSQL_PASSWORD=hempfield
    ports:
      - '3308:3306'

volumes:
  db_data:
