# Generated by Django 3.2.12 on 2022-08-03 21:04

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teammanagement", "0005_alter_player_player_link"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Velocity",
                    fields=[
                        ("date", models.DateField()),
                        ("velocity", models.PositiveSmallIntegerField()),
                        (
                            "velocity_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        (
                            "player",
                            models.ForeignKey(
                                db_column="player_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="velocity_records",
                                to="teammanagement.player",
                                verbose_name="Player",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name_plural": "Velocities",
                        "db_table": "Velocity",
                        "ordering": ["date"],
                    },
                ),
                migrations.CreateModel(
                    name="VelocityType",
                    fields=[
                        (
                            "velocity_type_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        ("name", models.CharField(max_length=25, unique=True)),
                        ("order", models.PositiveSmallIntegerField(default=0)),
                    ],
                    options={
                        "verbose_name": "Velocity Type",
                        "verbose_name_plural": "Velocity Types",
                        "db_table": "VelocityType",
                        "ordering": ["order"],
                    },
                    managers=[
                        ("leaderboard_objects", django.db.models.manager.Manager()),
                    ],
                ),
                migrations.CreateModel(
                    name="VelocityImprovement",
                    fields=[
                        (
                            "velocity_improvement_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        ("improvement", models.SmallIntegerField(default=0)),
                        (
                            "baseline",
                            models.ForeignKey(
                                db_column="baseline_velocity_id",
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="baseline_velocity_improvements",
                                to="velocities.velocity",
                                verbose_name="Baseline",
                            ),
                        ),
                        (
                            "latest",
                            models.ForeignKey(
                                db_column="latest_velocity_id",
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="latest_velocity_improvements",
                                to="velocities.velocity",
                                verbose_name="Latest",
                            ),
                        ),
                        (
                            "player",
                            models.ForeignKey(
                                db_column="player_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="velocity_improvements",
                                to="teammanagement.player",
                                verbose_name="Player",
                            ),
                        ),
                        (
                            "ttype",
                            models.ForeignKey(
                                db_column="velocity_type_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="improvements",
                                to="velocities.velocitytype",
                                verbose_name="Velocity Type",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Velocity Improvement",
                        "verbose_name_plural": "Velocity Improvements",
                        "db_table": "VelocityImprovement",
                        "ordering": [
                            "-player__is_active",
                            "player__last_name",
                            "ttype__order",
                        ],
                    },
                ),
                migrations.AddField(
                    model_name="velocity",
                    name="ttype",
                    field=models.ForeignKey(
                        db_column="velocity_type_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="velocities",
                        to="velocities.velocitytype",
                        verbose_name="Velocity Type",
                    ),
                ),
                migrations.CreateModel(
                    name="Pulldown",
                    fields=[
                        ("date", models.DateField()),
                        ("velocity", models.PositiveSmallIntegerField()),
                        (
                            "pulldown_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        (
                            "ball_weight",
                            models.CharField(
                                choices=[
                                    ("3", "3oz"),
                                    ("4", "4oz"),
                                    ("5", "5oz"),
                                    ("6", "6oz"),
                                    ("7", "7oz"),
                                ],
                                max_length=1,
                            ),
                        ),
                        (
                            "player",
                            models.ForeignKey(
                                db_column="player_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="pulldown_records",
                                to="teammanagement.player",
                                verbose_name="Player",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "Pulldown",
                        "ordering": ["date"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
