# Generated by Django 3.2.12 on 2022-08-04 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teammanagement', '0005_alter_player_player_link'),
        ('velocities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='velocitytype',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='PlyoDrillVelocity',
            fields=[
                ('date', models.DateField()),
                ('velocity', models.PositiveSmallIntegerField()),
                ('plyo_drill_velocity_id', models.AutoField(primary_key=True, serialize=False)),
                ('drill', models.CharField(choices=[('FF', 'Funnel Front'), ('SB', 'Step Back'), ('DS', 'Drop Step'), ('WW', 'Walking Windup')], max_length=2)),
                ('ball_weight', models.CharField(choices=[('450', '450g'), ('225', '225g'), ('150', '150g'), ('100', '100g')], max_length=3)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='plyodrillvelocity_records', to='teammanagement.player', verbose_name='Player')),
            ],
            options={
                'db_table': 'PlyoDrillVelocity',
                'ordering': ['date'],
            },
        ),
    ]
