# Generated by Django 3.2.12 on 2022-08-05 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velocities', '0002_auto_20220804_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plyodrillvelocity',
            options={'ordering': ['date'], 'verbose_name': 'Plyo Drill Velocity', 'verbose_name_plural': 'Plyo Drill Velocities'},
        ),
    ]
