# Generated by Django 3.2.12 on 2022-08-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velocities', '0003_alter_plyodrillvelocity_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VelocityImprovement',
        ),
    ]
