# Generated by Django 3.2.12 on 2022-08-21 21:19

from django.db import migrations


def populate_velocity_positions(apps, schema_editor):
    Velocity = apps.get_model("velocities", "Velocity")
    for velocity in Velocity.objects.all():
        if velocity.ttype.name == "Exit":
            velocity.position = "E"
        elif velocity.ttype.name == "Pitching":
            velocity.position = "P"
        elif velocity.ttype.name == "Outfield":
            velocity.position = "OF"
        elif velocity.ttype.name == "Infield":
            velocity.position = "IF"
        else:
            velocity.position = "C"
        velocity.save()


class Migration(migrations.Migration):

    dependencies = [
        ("velocities", "0005_velocity_position"),
    ]

    operations = [migrations.RunPython(populate_velocity_positions)]
