# Generated by Django 3.2.12 on 2022-08-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocities', '0006_auto_20220821_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='velocity',
            name='ttype',
        ),
        migrations.AlterField(
            model_name='velocity',
            name='position',
            field=models.CharField(choices=[('E', 'Exit'), ('P', 'Pitching'), ('OF', 'Outfield'), ('IF', 'Infield'), ('C', 'Catching')], max_length=2),
        ),
    ]
