# Generated by Django 3.2.12 on 2022-08-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velocities', '0007_auto_20220821_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VelocityType',
        ),
    ]
