# Generated by Django 3.2.12 on 2022-09-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velocities', '0008_delete_velocitytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pulldown',
            options={'ordering': ['date'], 'verbose_name': 'Weighted Ball Velocity', 'verbose_name_plural': 'Weighted Ball Velocities'},
        ),
        migrations.AlterModelTable(
            name='pulldown',
            table='WeightedBallVelocity',
        ),
    ]
