# Generated by Django 3.2.12 on 2022-09-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("velocities", "0009_auto_20220905_1456"),
    ]

    operations = [
        migrations.RenameModel("Pulldown", "WeightedBallVelocity"),
    ]
