# Generated by Django 3.2.12 on 2022-09-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teammanagement', '0005_alter_player_player_link'),
        ('velocities', '0010_auto_20220905_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightedballvelocity',
            name='drill',
            field=models.CharField(choices=[('M', 'Mound'), ('P', 'Pulldown')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='weightedballvelocity',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='weightedballvelocity_records', to='teammanagement.player', verbose_name='Player'),
        ),
    ]
