# Generated by Django 3.1.6 on 2021-04-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerprogress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='distance_type',
            new_name='ttype',
        ),
        migrations.RenameField(
            model_name='distanceimprovement',
            old_name='distance_type',
            new_name='ttype',
        ),
        migrations.RenameField(
            model_name='lift',
            old_name='lift_type',
            new_name='ttype',
        ),
        migrations.RenameField(
            model_name='liftimprovement',
            old_name='lift_type',
            new_name='ttype',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='time_type',
            new_name='ttype',
        ),
        migrations.RenameField(
            model_name='timeimprovement',
            old_name='time_type',
            new_name='ttype',
        ),
        migrations.RenameField(
            model_name='velocity',
            old_name='velocity_type',
            new_name='ttype',
        ),
        migrations.RenameField(
            model_name='velocityimprovement',
            old_name='velocity_type',
            new_name='ttype',
        ),
    ]
