# Generated by Django 3.2.3 on 2021-06-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerprogress', '0002_auto_20210613_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancetype',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='lifttype',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='timetype',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='velocitytype',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
