# Generated by Django 3.2.3 on 2021-08-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerprogress', '0003_auto_20210813_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='ttype',
            field=models.ForeignKey(db_column='distance_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='playerprogress.distancetype', verbose_name='Distance Type'),
        ),
        migrations.AlterField(
            model_name='distanceimprovement',
            name='ttype',
            field=models.ForeignKey(db_column='distance_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='playerprogress.distancetype', verbose_name='Distance Type'),
        ),
        migrations.AlterField(
            model_name='distancetype',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='lift',
            name='ttype',
            field=models.ForeignKey(db_column='lift_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='lifts', to='playerprogress.lifttype', verbose_name='Lift Type'),
        ),
        migrations.AlterField(
            model_name='liftimprovement',
            name='ttype',
            field=models.ForeignKey(db_column='lift_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='playerprogress.lifttype', verbose_name='Lift Type'),
        ),
        migrations.AlterField(
            model_name='lifttype',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='strengthincrement',
            name='lift_type',
            field=models.ForeignKey(db_column='lift_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='strength_increments', to='playerprogress.lifttype', verbose_name='Lift Type'),
        ),
        migrations.AlterField(
            model_name='time',
            name='ttype',
            field=models.ForeignKey(db_column='time_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='times', to='playerprogress.timetype', verbose_name='Time Type'),
        ),
        migrations.AlterField(
            model_name='timeimprovement',
            name='ttype',
            field=models.ForeignKey(db_column='time_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='playerprogress.timetype', verbose_name='Time Type'),
        ),
        migrations.AlterField(
            model_name='timetype',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='velocity',
            name='ttype',
            field=models.ForeignKey(db_column='velocity_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='velocities', to='playerprogress.velocitytype', verbose_name='Velocity Type'),
        ),
        migrations.AlterField(
            model_name='velocityimprovement',
            name='ttype',
            field=models.ForeignKey(db_column='velocity_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='playerprogress.velocitytype', verbose_name='Velocity Type'),
        ),
        migrations.AlterField(
            model_name='velocitytype',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
