# Generated by Django 3.2.7 on 2021-09-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerprogress', '0004_auto_20210814_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distanceimprovement',
            options={'ordering': ['-player__is_active', 'player__last_name', 'ttype__order'], 'verbose_name': 'Distance Improvement', 'verbose_name_plural': 'Distance Improvements'},
        ),
        migrations.AlterModelOptions(
            name='liftimprovement',
            options={'ordering': ['-player__is_active', 'player__last_name', 'ttype__order'], 'verbose_name': 'Lift Improvement', 'verbose_name_plural': 'Lift Improvements'},
        ),
        migrations.AlterModelOptions(
            name='timeimprovement',
            options={'ordering': ['-player__is_active', 'player__last_name', 'ttype__order'], 'verbose_name': 'Time Improvement', 'verbose_name_plural': 'Time Improvements'},
        ),
        migrations.AlterModelOptions(
            name='velocityimprovement',
            options={'ordering': ['-player__is_active', 'player__last_name', 'ttype__order'], 'verbose_name': 'Velocity Improvement', 'verbose_name_plural': 'Velocity Improvements'},
        ),
    ]
