# Generated by Django 3.2.12 on 2022-07-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerprogress', '0006_auto_20220515_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyweight',
            options={'ordering': ['date'], 'verbose_name': 'Body Weight', 'verbose_name_plural': 'Body Weights'},
        ),
        migrations.AlterModelOptions(
            name='distance',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='lift',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='velocity',
            options={'ordering': ['date'], 'verbose_name_plural': 'Velocities'},
        ),
        migrations.AlterModelManagers(
            name='bodyweightimprovement',
            managers=[
            ],
        ),
    ]
