# Generated by Django 3.2.12 on 2022-07-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teammanagement', '0005_alter_player_player_link'),
        ('playerprogress', '0007_auto_20220717_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulldown',
            fields=[
                ('pulldown_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ball_weight', models.CharField(choices=[('3', '3oz'), ('4', '4oz'), ('5', '5oz'), ('6', '6oz'), ('7', '7oz')], max_length=1)),
                ('velocity', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='pulldowns', to='teammanagement.player', verbose_name='Player')),
            ],
            options={
                'db_table': 'Pulldown',
                'ordering': ['date'],
            },
        ),
    ]
