# Generated by Django 3.2.12 on 2022-09-05 17:50

from django.db import migrations


def populate_college_division_choices(apps, schema_editor):
    College = apps.get_model("colleges", "College")
    for college in College.objects.all():
        if college.division.name == "Division III":
            college.division_choice = "NC3"
        elif college.division.name == "Division II":
            college.division_choice = "NC2"
        else:
            college.division_choice = "NC1"
        college.save()


class Migration(migrations.Migration):

    dependencies = [
        ("colleges", "0002_college_division_choice"),
    ]

    operations = [migrations.RunPython(populate_college_division_choices)]
