# Generated by Django 3.2.12 on 2022-09-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_auto_20220905_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='division_choice',
            new_name='division',
        ),
    ]
