# Generated by Django 3.2.3 on 2021-08-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerresources', '0003_auto_20210813_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsiteLink',
            new_name='ArticleLink',
        ),
        migrations.RenameModel(
            old_name='WebsiteLinkType',
            new_name='LinkType',
        ),
        migrations.AlterModelOptions(
            name='articlelink',
            options={'ordering': ['order'], 'verbose_name': 'Article Link', 'verbose_name_plural': 'Article Links'},
        ),
        migrations.AlterModelTable(
            name='articlelink',
            table='ArticleLink',
        ),
    ]
