# Generated by Django 3.2.3 on 2021-08-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerresources', '0004_auto_20210813_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlelink',
            old_name='website_link_id',
            new_name='article_link_id',
        ),
        migrations.RenameField(
            model_name='articlelink',
            old_name='website_link_type_id',
            new_name='link_type_id',
        ),
        migrations.AlterField(
            model_name='articlelink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resources-article-link-images'),
        ),
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('video_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=150)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('link_type_id', models.ForeignKey(db_column='link_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='video_links', to='playerresources.linktype', verbose_name='Link Type')),
            ],
            options={
                'verbose_name': 'Video Link',
                'verbose_name_plural': 'Video Links',
                'db_table': 'VideoLink',
                'ordering': ['order'],
            },
        ),
    ]
