# Generated by Django 3.2.3 on 2021-08-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerresources', '0006_alter_articlelink_link_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelink',
            name='link_type_id',
            field=models.ForeignKey(db_column='link_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='playerresources.linktype', verbose_name='Link Type'),
        ),
        migrations.AlterField(
            model_name='videolink',
            name='link_type_id',
            field=models.ForeignKey(db_column='link_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='playerresources.linktype', verbose_name='Link Type'),
        ),
    ]
