# Generated by Django 3.2.12 on 2022-05-15 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgradprep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCamp',
            fields=[
                ('college_camp_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('link', models.URLField(max_length=80)),
                ('college', models.ForeignKey(db_column='college_id', on_delete=django.db.models.deletion.CASCADE, related_name='college_camps', to='postgradprep.college', verbose_name='College')),
            ],
            options={
                'verbose_name': 'College Camp',
                'verbose_name_plural': 'College Camps',
                'db_table': 'CollegeCamp',
                'ordering': ['-date'],
            },
        ),
    ]
