# Generated by Django 3.2.12 on 2022-08-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgradprep', '0003_alter_collegecamp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegecamp',
            name='link',
            field=models.URLField(max_length=100),
        ),
    ]
