# Generated by Django 3.2.12 on 2022-08-14 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("colleges", "0001_initial"),
        ("alumni", "0006_alter_alumniplayer_college"),
        ("postgradprep", "0004_alter_collegecamp_link"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="collegecamp",
                    name="college",
                    field=models.ForeignKey(
                        db_column="college_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="college_camps",
                        to="colleges.college",
                        verbose_name="College",
                    ),
                ),
                migrations.DeleteModel(
                    name="College",
                ),
                migrations.DeleteModel(
                    name="Division",
                ),
            ],
            database_operations=[],
        ),
    ]
