# Generated by Django 3.2.3 on 2021-05-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelink',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='websitelink',
            name='url',
            field=models.URLField(max_length=150),
        ),
    ]
