# Generated by Django 3.2.3 on 2021-08-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20210813_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktype',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
