# Generated by Django 3.2.7 on 2021-09-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20210813_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlelink',
            old_name='link_type_id',
            new_name='link_type',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_type_id',
            new_name='book_type',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document_type_id',
            new_name='document_type',
        ),
        migrations.RenameField(
            model_name='videolink',
            old_name='link_type_id',
            new_name='link_type',
        ),
    ]
